### ISSUE TITLE
Not able to make it run on Windows

### ISSUE THREAD

**Issue by shatgupt** [docker-exec/dexec#10]
I am not able to make it run in Windows 7.
Have installed docker for Windows (http://docs.docker.com/installation/windows/) and docker is started with boot2docker. But dexec complains: 2015/04/08 20:34:25 Docker not found.

How can I make dexec use docker via boot2docker?

**Comment by andystanton** [comment]
hi @shatgupt - my apologies but I didn't test on windows! 😱

I will resolve this for the next release, and thank you for your feedback.
