### ISSUE TITLE
Remote execution

### ISSUE THREAD

**Issue by mancvso** [docker-exec/dexec#13]
I think the next step would be enabling the use of an external Docker server (for Windows machines that have acces to a Linux box w/Docker).
I know that it may involve ssh commands or acces to the Docker remote API and that is a complete different beast.

Does the current architecture allows the use of an external docker daemon?
Amazing project.

**Comment by andystanton** [comment]
Thanks for the feedback @mancvso! Can you give me an example of the commands that you would want to run on the command line?

**Comment by andystanton** [comment]
I think I now get what you mean @mancvso - I've raised #35 in which I'll switch shelled out calls to Docker remote API calls.
