### ISSUE TITLE
UnicodeEncodeError on Python3

### ISSUE THREAD

**Issue by hanksudo** [docker-exec/dexec#26]
**helloworld.py**
```
# -*- coding: utf-8 -*-
print('Hello, 世界！')
```
`$ dexec helloworld.py`
`UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-9: ordinal not in range(128)`

**Comment by andystanton** [comment]
Confirmed - debian:8.0 base image provides shell that uses ascii by default. Python 3 uses this as its default character encoding.

## Steps to reproduce without dexec
```
$ docker run -i --rm -v "$(pwd -P)/unicode.py":/unicode.py -t debian:8.0
$ apt-get update -qq && apt-get install -y python3
$ python3 unicode.py

Traceback (most recent call last):
  File "unicode.py", line 2, in <module>
    print('Hello, \u4e16\u754c\uff01')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-9: ordinal not in range(128)
```

## Suggested fix
Set ```LANG``` environment variable to C.UTF-8 in all Dockerfiles.
```
$ export LANG=C.UTF-8
$ python3 unicode.py

Hello, 世界！
```

## Temporary workaround
Python 2 doesn't seem to have this problem so can be used instead. This can be done by overriding the image:
```sh
$ dexec -s dexec/python2 unicode.py
```

**Comment by andystanton** [comment]
This is fixed in master @hanksudo.

Note that the name of the Docker images has changed from ```dexec/python``` to ```dexec/lang-python```. This will mean that they will be downloaded again with the new name but the original ones will stay on your system taking up space. Therefore I recommend deleting all existing dexec images with something like:

```sh
docker ps -a | grep dexec | awk '{print $1}' | xargs docker rm -f
docker images | grep dexec | awk '{print $3}' | xargs docker rmi -f
```

These instructions will be in the 1.0.2 release notes too.

**Comment by hanksudo** [comment]
@andystanton thanks, it works. good job.
