### ISSUE TITLE
Temporary file can not be found?

### ISSUE THREAD

**Issue by alixaxel** [docker-exec/dexec#41]
I'm always getting the following error whenever I try to dexec any file (regardless of language):

> /tmp/dexec/image-common/dexec-script.sh: line 28: /home/alix/foo.js_tmp: No such file or directory

Here's some info that could be useful:

```
alix@ThinkPad:~$ docker info
Containers: 0
Images: 15
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-28-generic
Operating System: Ubuntu 15.04
CPUs: 4
Total Memory: 7.496 GiB
Name: ThinkPad
ID: R7GC:HCG4:T7R2:3T62:DLYM:XBFR:MLQH:BD5M:VDUN:OP2Y:G4VA:GSYF
WARNING: No swap limit support

alix@ThinkPad:~$ docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:21:21 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:21:21 UTC 2015
 OS/Arch:      linux/amd64

alix@ThinkPad:~$ sudo dexec /home/alix/foo.js
Unable to find image 'dexec/lang-node:1.0.2' locally
1.0.2: Pulling from dexec/lang-node
a1589201fdd2: Pull complete 
059c05383383: Pull complete 
c99874c78a04: Pull complete 
5c979081e8a8: Pull complete 
0f81d39fb182: Pull complete 
1ea59cd801ad: Pull complete 
3f53c4f49f02: Already exists 
3cb35ae859e7: Already exists 
41b730702607: Already exists 
Digest: sha256:ef25b334cf651b8ba889e4eff5c80c9974a3fdaa2b46bab4e70e44fa612e3320
Status: Downloaded newer image for dexec/lang-node:1.0.2
/tmp/dexec/image-common/dexec-script.sh: line 28: /home/alix/foo.js_tmp: No such file or directory
```

I'm running dexec 1.0.2, I tried both the binary from Bintray and I also compiled the code locally.

Is there anything I'm missing? I tried the same in a Mac OS and everything worked perfectly.

**Comment by andystanton** [comment]
Hi @alixaxel 

Currently dexec doesn't support absolute paths. This is because it has to mount the directory containing the source files in the running container and this is much easier if the source files are assumed to be relative to the current working directory.

I can think of two options that you could try to work around this. You can specify the path like this: https://github.com/docker-exec/dexec#specify-location-of-source-files

```sudo dexec -C /home/alix foo.js```

or just cd to the directory and run it.

```
cd /home/alix && sudo dexec foo.js
```

Let me know if that helps!

**Comment by alixaxel** [comment]
@andystanton Works flawlessly! I was doing something wrong after all. :)

Maybe this should be put into the README if it's not already there.

Thanks!

**Comment by andystanton** [comment]
👍glad it worked!
