### ISSUE TITLE
get "Docker not found" when trying to use linux binary.

### ISSUE THREAD

**Issue by mitchcapper** [docker-exec/dexec#57]
Tried two machines an Ubuntu and a Gentoo box. on both did the following:
curl -L https://bintray.com/artifact/download/dexec/release/dexec_1.0.3_linux_amd64.tar.gz  | tar -xz && ./dexec_1.0.3_linux_amd64/dexec
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  988k  100  988k    0     0   977k      0  0:00:01  0:00:01 --:--:--  977k
2016/04/14 16:44:05 Docker not found

however docker is in path (/usr/bin/docker)  I can strace and see it does find it.  I did try grepping the source for the "docker not found" error message but couldn't find it.

**Comment by andystanton** [comment]
@mitchcapper do you need root to run docker on those systems? If so, you'll also need to run dexec as root.

**Comment by mitchcapper** [comment]
no I do not, but also tried running as root.

**Comment by andystanton** [comment]
@mitchcapper the error is because version 1.0.3 is using handrolled Docker integration code which isn't compatible with more recent versions of Docker on Linux.

I changed this a while ago to use https://github.com/fsouza/go-dockerclient in master but never got around to releasing it. Can you confirm what versions of Ubuntu and Gentoo, as well as the version of Docker on each, so I can test against those?

Cheers

**Comment by andystanton** [comment]
@mitchcapper I've released that change as v1.0.4. Can you test again?

**Comment by mitchcapper** [comment]
Well further maybe should be a different bug report now, it just dumps help:
```
:~/dexec_1.0.5_linux_amd64$ ./dexec a.cpp
Name:
        ./dexec - Execute code in many languages with Docker!

Usage:
        ./dexec [options] <source files...>

Options:
        -C <dir>                            Specify source directory
        --arg, -a <argument>                Pass <argument> to the executing code
        --build-arg, -b <build argument>    Pass <build argument> to compiler
        --include, -i <file|path>           Mount local <file|path> in dexec container
        --extension, -e <extension>         Override the image used by <extension>
        --image, -m <name>                  Override the image used by <name>
        --update, -u                        Force update of image
        --clean                             Remove all local dexec images
        --help, -h                          Show help
        --version, -v                       Display version info
```

**Comment by andystanton** [comment]
Looks like a different bug - single character filenames don't seem to be picked up as source files. I've raised #58 but in the meantime, try renaming giving the filename before the extension a longer name than `a`.

**Comment by mitchcapper** [comment]
Yep that fixed it closing this.

**Comment by andystanton** [comment]
Ace, thanks a lot for taking the time to raise the issue and follow up.
