### ISSUE TITLE
Homebrew requires --HEAD

### ISSUE THREAD

**Issue by christophberger** [docker-exec/dexec#59]
Running the brew command as listed in the readme (`brew install docker-exec/formula/dexec`) results in an error message:

```
Error: docker-exec/formula/dexec is a head-only formula
Install with `brew install --HEAD docker-exec/formula/dexec`
```

With the --HEAD option, brewing succeeds.

**Comment by andystanton** [comment]
Thanks for reporting this @christophberger - I've added the latest tagged version to the Homebrew formula so it will install that by default, but left the head reference so you can still use --HEAD to get the version currently in master.

Let me know if you have any more issues with this.

**Comment by christophberger** [comment]
Thanks @andystanton, it works now as advertised :)
