### ISSUE TITLE
Doesn't work under Windows 7 (docker toolbox)

### ISSUE THREAD

**Issue by sshikov** [docker-exec/dexec#64]
Failed on sed command inside .sh script because mounted volume is not a file, as expected, but a directory.

As I can understand, directory mount is only possible option for windows.

**Comment by andystanton** [comment]
Hi @sshikov 

Can you confirm the path to the source files on your computer?

I think with Docker toolbox on both Windows & Mac there is a limitation where you can only mount directories from C:\Users. dexec starts a container and mounts the source file you're executing in it, so the limitation is that the source files must be in a path under C:\Users.

**Comment by sshikov** [comment]
I think here is some misunderstanding from my side.

As far as I know, on windows (for docker toolbox, as described here: https://docs.docker.com/engine/tutorials/dockervolumes/) you can mount directories only. 

But dexec expects that source file will be mounted.

Just have a try to mount directory within c:\Users, works fine. Thanks!
