### ISSUE TITLE
is there an execution timeout for programs that just _may_ take forever?

### ISSUE THREAD

**Issue by gideondsouza** [docker-exec/dexec#67]
just as the title says:

```
what if i executed 
while(true){print "hey";}
```
is there something that will kill the program at some point?

**Comment by andystanton** [comment]
There isn't, but this is a great suggestion for a feature. I'll add it when I get some time, or I'm happy to accept a pull request.

**Comment by gideondsouza** [comment]
cool. Idea be happy to send PR  but I’d need a starting point not super familiar with docked still.

**Comment by andystanton** [comment]
Added in #69 by @johnhany97.
