### ISSUE TITLE
dexec python will only work for python 3

### ISSUE THREAD

**Issue by JoePython1** [docker-exec/dexec#9]
dexec python will only work for python 3.
How can i make it support python 2.x

**Comment by andystanton** [comment]
@JoePython1 currently only python 3 is supported. I will add a python2 image and feature to be implemented in #11 will allow you to choose whether to use python 2 or 3, providing a mechanism for what you want.

Unfortunately python 2 and 3 share the same file extension, so one will need to be picked as the default image to run on .py files. I'm open to what that should be.

**Comment by JoePython1** [comment]
Howabout If dexec can read the shebang line, you can expect something like /usr/bin/python2 for python2 or just /usr/bin/python for python3. Just saying. Thanks for the good work.

**Comment by andystanton** [comment]
That's a good suggestion @JoePython1 but I want dexec to be relatively lightweight and not have to parse source files if possible (there is some shebang parsing but that's done in the bash script that runs on the images).

I've released v1.0.1 with the change I described but feel free to raise a PR with your suggestion if you have a good idea about how to implement it!
